### PR TITLE
Update pyo3 + test python feature in CI

### PR DESCRIPTION
**Pull request by Keats**
Closes DEV-3964

### CODE REVIEW

**Comment by Keats** [comment]
cc @bovee what do you think of the new API?

**Comment by bovee** [comment]
@Keats This is great (I really love `py_try!`, `NoSuchName`, and `#[non_exhaustive]`).

The one thing (and I'm not even sure if it's a good idea) is that I might consider exposing `get_name` and/or `get_rank` as faster/lower memory alternatives to the index syntax; I think the index syntax here is really nice, but I worry people may start to expect the TaxonomyNode objects to e.g. be able to return their parents as TaxonomyNode objects (which is a pattern common to other taxonomy libraries that I was trying to get away from; I think this may be why I'm not totally in love with the `get_` prefixes everywhere either).

**Comment by Keats** [comment]
>  I might consider exposing get_name and/or get_rank as faster/lower memory alternatives to the index syntax;

What do you mean? This is the same code underneath right now and I don't think we can make it faster/use less memory.

> I think this may be why I'm not totally in love with the get_ prefixes everywhere either

We could remove the `get_` prefixes without any issues, there isn't a specific reason it's there.

**Comment by bovee** [comment]
Yeah, it's a super micro-optimization. Calling `taxonomy['id'].name` will do four allocations for the name, rank, parent strings, and node object itself, but calling just `taxonomy.name('id')` does one; the overhead might be swamped by the python interop though so maybe it's not an issue?

**Comment by Keats** [comment]
Ah I see what you mean. I could mention it in the docs but I don't think it will be noticeable given the string length

**Pull request merged**
