### PR TITLE
Add missing strain rank

### PR DESCRIPTION
**Pull request by lv43apo91**
I think this may have just been an omission...adding back in the strain rank.
Would appreciate if you could push a minor release after this is accepted...thanks!

### CODE REVIEW

**Comment by lv43apo91** [comment]
Bump @Keats @audy ?

**Comment by Keats** [comment]
LGTM, all the CI failures are unrelated. Any reasons this wasn't present @audy ?

**Comment by lv43apo91** [comment]
Bump @audy ? Or @Keats can we just go ahead and merge and bump conda version?

**Comment by audy** [comment]
@lv43apo91 LGTM. Thanks for catching and sorry for the slow response.

**Pull request merged**
